"""001 base turnos con EXCLUDE"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '04e8b6447bc2'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")  # EXCLUDE sobre '=' exige btree_gist
    op.create_table('tenants',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('chairs',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patients',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('dni', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('professionals',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('services',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('duracion_min', sa.Integer(), nullable=False),
    sa.Column('precio_base', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appointments',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('patient_id', sa.BigInteger(), nullable=False),
    sa.Column('professional_id', sa.BigInteger(), nullable=False),
    sa.Column('chair_id', sa.BigInteger(), nullable=False),
    sa.Column('service_id', sa.BigInteger(), nullable=False),
    sa.Column('inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fin', sa.DateTime(timezone=True), nullable=False),
    sa.Column('estado', sa.Text(), nullable=False),
    sa.Column('sobreturno', sa.Boolean(), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=True),
    postgresql.ExcludeConstraint((sa.column('chair_id'), '='), (sa.text("tstzrange(inicio, fin, '[)')"), '&&'), where=sa.text("estado IN ('reservado', 'confirmado', 'atendido')"), using='gist', name='ex_appointments_chair_rango'),
    postgresql.ExcludeConstraint((sa.column('professional_id'), '='), (sa.text("tstzrange(inicio, fin, '[)')"), '&&'), where=sa.text("estado IN ('reservado', 'confirmado', 'atendido')"), using='gist', name='ex_appointments_professional_rango'),
    sa.CheckConstraint("estado IN ('reservado','confirmado','atendido','cancelado','ausente')", name='ck_appointments_estado'),
    sa.ForeignKeyConstraint(['chair_id'], ['chairs.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['professional_id'], ['professionals.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointments_tenant_id'), 'appointments', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appointments_tenant_id'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_table('services')
    op.drop_table('professionals')
    op.drop_table('patients')
    op.drop_table('chairs')
    op.drop_table('tenants')
    # ### end Alembic commands ###
