"""003 exclude ignora sobreturnos"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '5d4c0a3d664d'
down_revision: str | None = '8e6b885de227'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


PREDICADO_NUEVO = "estado IN ('reservado','confirmado','atendido') AND sobreturno = false"
PREDICADO_VIEJO = "estado IN ('reservado','confirmado','atendido')"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Autogenerate no detecta cambios en el predicado WHERE de EXCLUDE: recreación manual.
    op.execute("ALTER TABLE appointments DROP CONSTRAINT ex_appointments_professional_rango")
    op.execute("ALTER TABLE appointments DROP CONSTRAINT ex_appointments_chair_rango")
    op.execute(
        "ALTER TABLE appointments ADD CONSTRAINT ex_appointments_professional_rango "
        f"EXCLUDE USING gist (professional_id WITH =, tstzrange(inicio, fin, '[)') WITH &&) "
        f"WHERE ({PREDICADO_NUEVO})"
    )
    op.execute(
        "ALTER TABLE appointments ADD CONSTRAINT ex_appointments_chair_rango "
        f"EXCLUDE USING gist (chair_id WITH =, tstzrange(inicio, fin, '[)') WITH &&) "
        f"WHERE ({PREDICADO_NUEVO})"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE appointments DROP CONSTRAINT ex_appointments_professional_rango")
    op.execute("ALTER TABLE appointments DROP CONSTRAINT ex_appointments_chair_rango")
    op.execute(
        "ALTER TABLE appointments ADD CONSTRAINT ex_appointments_professional_rango "
        f"EXCLUDE USING gist (professional_id WITH =, tstzrange(inicio, fin, '[)') WITH &&) "
        f"WHERE ({PREDICADO_VIEJO})"
    )
    op.execute(
        "ALTER TABLE appointments ADD CONSTRAINT ex_appointments_chair_rango "
        f"EXCLUDE USING gist (chair_id WITH =, tstzrange(inicio, fin, '[)') WITH &&) "
        f"WHERE ({PREDICADO_VIEJO})"
    )
    # ### end Alembic commands ###
