"""002 server defaults"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '8e6b885de227'
down_revision: str | None = '04e8b6447bc2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("chairs", "activo", server_default="true")
    op.alter_column("appointments", "estado", server_default="reservado")
    op.alter_column("appointments", "sobreturno", server_default="false")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("chairs", "activo", server_default=None)
    op.alter_column("appointments", "estado", server_default=None)
    op.alter_column("appointments", "sobreturno", server_default=None)
    # ### end Alembic commands ###
